Add cookie name parameter
xavierbriole/react-cookienotice pull request #52
Opened 2021-01-12 13:02 UTC by allexks

Implementing #51

2021-01-12 13:06 UTC, allexks commented
Sorry for the failing pipeline, I am new to the JS / React world. I will create tests for the new feature whenever as soon as I can.

2021-01-12 17:52 UTC, xavierbriole commented
Thank you for the PR 🙏 
You're the first contributor of this repository! 🎉 

Dont worry, I will review these changes and help you pass the pipeline! 🚀

2021-01-12 18:18 UTC, xavierbriole requested changes
That's good! For the pipeline, just run `yarn run format`if you don't have prettier in your IDE.

Just waiting for the tests and let's go for the next version !

2021-01-12 18:18 UTC, xavierbriole commented on src/Validator/index.js
> +export const validateCookieName = (parameter?: any): string => {
Can you place this function just before the `validateDarkTheme()` function please ?

2021-01-12 18:18 UTC, xavierbriole commented on src/Components/CookieNotice.js
> +  cookieName?: string,
Can you place this line between `cookieExpiration` prop and `darkTheme` prop please ?

2021-01-12 18:18 UTC, xavierbriole commented on src/Components/CookieNotice.js
> +  validateCookieName,
And this line just below `validateCookieExpiration` import ! (I like ordering lol)

2021-01-13 13:19 UTC, allexks commented
I wrote tests for the validator but am not sure how to write tests for `CookieNotice.js` to cover the lines suggested by CodeCov, could you help with this?

2021-01-13 13:32 UTC, xavierbriole commented
Hmmm, yes I will check asap.

2021-01-17 12:33 UTC, xavierbriole commented
@allexks hello, I wrote CookieNotice tests to be 100% code coverage on the project 🎉 

Can you please rebase your branch, adapt your tests if needed and check if the pipeline pass ?

2021-01-21 12:33 UTC, xavierbriole requested changes
Sorry for the response/review latence, I don't have a lot of time ahah.
I did some last reviews. Thanks !!

2021-01-21 12:33 UTC, xavierbriole commented on src/Components/CookieNotice.test.js
>    describe('should set cookie', () => {
Can you replace this test suite into a single test `it('should set cookie', () => {})` that mock : 
```js
mock(validateCookieExpiration).mockImplementation(() => 'mockedCookieExpiration')
mock(validateCookieName).mockImplementation(() => 'mockedCookieName')
```

2021-01-24 12:49 UTC, xavierbriole approved these changes

2021-01-24 12:50 UTC, merged